// ศูนย์กลาง icon ทั้งแอป — map ชื่อ logical → lucide component
// import ที่เดียวเพื่อคุมความสม่ำเสมอ (ขนาด/เส้น/น้ำหนักเท่ากันหมด) แทน emoji เดิม
export {
  Play,
  Square,
  RotateCw,
  ScrollText,
  Globe,
  FolderOpen,
  SquareTerminal,
  Star,
  Pencil,
  Trash2,
  Cpu,
  MemoryStick,
  Search,
  Plus,
  X,
  ArrowLeft,
  ArrowDown,
  ArrowRight,
  Folder,
  FolderSearch,
  Settings2,
  Container,
  Terminal,
  Hash,
  ChevronDown,
  Circle,
  CircleDot,
  Loader,
  PartyPopper,
  Hand,
  Inbox,
} from 'lucide-react';
